version: '2'
services:
    damocles-app:
        image: damocles
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://damocles-postgresql:5432/damocles
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    damocles-postgresql:
        extends:
            file: postgresql.yml
            service: damocles-postgresql
